project:
  type: website
  output-dir: docs

website:
  title: "70BiomColl_AdvDataVisR"
  navbar:
    title: "Tutorial: Advanced data visualization in R"
    right:
      - text: Contact
        href: https://schmidtpaul.github.io/
      - icon: github
        href: https://github.com/SchmidtPaul/70BiomColl_AdvDataVisR
        aria-label: GitHub
  page-footer: 
    left: |
      Inhalt {{< fa brands creative-commons >}} 
      2024 von [Dr. Paul Schmidt](https://schmidtpaul.github.io/), 
      [BioMath GmbH](www.biomath.de)<br>
      Alle Inhalte sind lizenziert als {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Erstellt mit [{{< fa brands r-project >}}](https://www.r-project.org/) 
      und [Quarto](https://quarto.org/).
    border: true
    background: "#00923f"
  site-url: https://github.com/SchmidtPaul/70BiomColl_AdvDataVisR

format:
  html:
    anchor-sections: true
    css: include/styles.css
    code-fold: false
    code-summary: "Click to show/hide code"
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-tools: true
    citations-hover: true
    footnotes-hover: true
    theme: include/theme.scss
    toc: true
  pdf:
    colorlinks: true
    number-sections: true
    toc: true

author:
  - name:
      given: Paul
      family: Schmidt
      literal: 'Paul Schmidt'
    # orcid: 0000-0003-1528-2082
    affiliations:
      - name: "BioMath GmbH"
        city: Hamburg
        country: Germany
        url: https://www.biomath.de/
      - name: "& Freelancer"
        url: https://schmidtpaul.github.io/

date: last-modified
published-title: "Last updated"

execute:
  warning: false
  message: false
  freeze: auto
  
citation: 
  publisher: "BioMath GmbH"
  note: "Presented at the 70th Biometrical Colloquium 2024 in Lübeck"