project:
  type: website
  output-dir: docs

website:
  title: "70BiomColl_AdvDataVisR"
  navbar:
    title: "Tutorial: Advanced data visualization in R"
    left:
      - href: index.qmd
        text: Home
    right:
      - text: Contact
        href: https://schmidtpaul.github.io/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

author:
  - name:
      given: Paul
      family: Schmidt
      literal: 'Paul Schmidt'
    # orcid: 0000-0003-1528-2082
    affiliations:
      - name: "BioMath GmbH"
        city: Hamburg
        country: Germany
        url: https://www.biomath.de/
      - name: "& Freelancer"
        url: https://schmidtpaul.github.io/

date: last-modified
published-title: "Last updated"

execute:
  warning: false
  message: false
  freeze: auto
  
fig-dpi: 300
fig-width: 5.5
fig-height: 3.5