project:
  type: website
  output-dir: docs

website:
  title: "70BiomColl_AdvDataVisR"
  navbar:
    title: "Tutorial: Advanced data visualization in R"
    right:
      - text: login
        href: login.qmd
      - text: Contact
        href: https://schmidtpaul.github.io/
      - icon: github
        href: https://github.com/SchmidtPaul/70BiomColl_AdvDataVisR
        aria-label: GitHub
  page-footer: 
    right:
      - text: '<p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>'
    border: true
    background: "#00923f"
  site-url: https://github.com/SchmidtPaul/70BiomColl_AdvDataVisR

format:
  html:
    anchor-sections: true
    css: styles.css
    code-fold: false
    code-summary: "Click to show/hide code"
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-tools: true
    citations-hover: true
    footnotes-hover: true
    theme: theme.scss
    toc: true
  pdf:
    colorlinks: true
    number-sections: true
    toc: true

author:
  - name:
      given: Paul
      family: Schmidt
      literal: 'Paul Schmidt'
    # orcid: 0000-0003-1528-2082
    affiliations:
      - name: "BioMath GmbH"
        city: Hamburg
        country: Germany
        url: https://www.biomath.de/
      - name: "& Freelancer"
        url: https://schmidtpaul.github.io/

date: last-modified
published-title: "Last updated"

execute:
  warning: false
  message: false
  freeze: auto
  
citation: 
  publisher: "70th Biometrical Colloquium 2024 in Lübeck"